### ISSUE TITLE
pdf-catalog opencart version 1.5.5.1

### ISSUE THREAD

**Issue by maxixus** [mithereal/opencart-pdf-catalog#10]
Hi I have a shop on opencart version 1.5.5.1 I installed yours module and faced such problem. In the error log:
- PHP Warning:  file_get_contents(/home/mokasiny/my site/www/home/mokasiny/.system/tmp/__tcpdf_imgmask_plain_4ec0c4b864329263887306103ed0ddd9) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in /home/mokasiny/my site/www/system/helper/tcpdf/include/tcpdf_static.php on line 2804
- PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/mokasiny/my site/www/index.php:106) in /home/mokasiny/my site/www/system/helper/tcpdf/tcpdf.php on line 7610

Please tell me what could be the problem? 
Thanks!

**Comment by mithereal** [comment]
this is a tcpdf issue there is no dir ".system" ill look into it later, try using one of the files i linked in the description, the temp dir is pointing incorrectly could also be permissions issue as the file is generated on the fly

**Comment by maxixus** [comment]
Sorry, I didn't quite understand which file I need to use. My English is so bad, maybe i something wrong translate. Sorry.
