### ISSUE TITLE
opencart 1.5.2.1 pdf-catalog page shows empty

### ISSUE THREAD

**Issue by danaildd** [mithereal/opencart-pdf-catalog#12]
Hi, i`m using the pdf-catalog in version 1.5.2.1 Anlthough it is not supported i added to the loader file :
public function helper($helper) {
        $file = DIR_SYSTEM . 'helper/' . $helper . '.php';

```
    if (file_exists($file)) {
        include_once($file);
        } else {
            trigger_error('Error: Could not load helper ' . $helper . '!');
            exit();
    }
}
```

Then i have no errors escept that the catalog page shows empty. Can you please make a small effort to help me. Thank you.

**Comment by mithereal** [comment]
if society would give me a job and i wasn't homeless i could help you, i have no dev machine, and am on a tablet, occasionally i use a friends computer, sorry.
