### ISSUE TITLE
Empty page at end of document 

### ISSUE THREAD

**Issue by poortyweb** [mithereal/opencart-pdf-catalog#13]
Hello 

Use the opencart version 2.2.0 and 1.5.5.1 with mijoshop joomla 3.1.5 and 2.8.2 Pdf Catalog. 

When generating the catalog, an empty page always appears at the end. 

I have tried using "display: none" but I have seen and read it does not work with tcpdf. 

I tried to change the foreach loop where <div class = "page_break" </ div> applied but have not succeeded. 

I have also tried using DeletePage () but neither worked. 

I can not think of anything else, you know it can be, and most importantly, can you help me

**Comment by mithereal** [comment]
fixed
