### ISSUE TITLE
Problem in OC 1.5.6

### ISSUE THREAD

**Issue by Dhustone** [mithereal/opencart-pdf-catalog#14]
Hi, I have installed and set up this extension in v1.5.6 of OC and everything looks great until I click on one of the categories at which point it returns a 'Page Cannot Be Found' message.

I'd be grateful for any ideas as to what might be causing this please?

**Comment by mithereal** [comment]
it works for me maybe you have a  seo url pack enabled could be breaking the route

**Comment by Dhustone** [comment]
I have the OC SEO URL's switched on in Settings. Do you mean that they need to be switch off for this extension to work?

**Comment by mithereal** [comment]
no you have some other issue this is working fine for me,
