### ISSUE TITLE
Add the option to display the description in native HTML

### ISSUE THREAD

**Issue by friscoMad** [mithereal/opencart-pdf-catalog#19]
Currently the description is stripped from all HTML, this can lead to some issues with formatting as it seems just like a lot of garbled text.

I know that it can cause some problems depending a lot of the descriptions and formats applied but at least give the user the option to enable it. It will not work great with description truncating but maybe we can borrow some code from Wordpress slug truncating as they preserve the format while limiting the article size.

**Comment by mithereal** [comment]
feature added
