### ISSUE TITLE
Error: Could not load helper tcpdf/tcpdf!

### ISSUE THREAD

**Issue by Kanonimpresor** [mithereal/opencart-pdf-catalog#25]
Hello, after install gives this error:

Notice: Error: Could not load helper tcpdf/tcpdf! in /home/bclasica/public_html/shop/vqmod/vqcache/vq2-system_engine_loader.php on line 34

Thank!

**Comment by friscoMad** [comment]
You need to download and install TCPDF at "system\helper\tcpdf"

**Comment by Kanonimpresor** [comment]
Thank Ramiro!
