### ISSUE TITLE
Fatal error: Allowed memory size....

### ISSUE THREAD

**Issue by Releaff** [mithereal/opencart-pdf-catalog#29]
Dear Mithereal,

I uploaded your extension with success. I even had a few succesfull PDF exports. However, from now on I only receive the following error in a new window:  

"Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 8019 bytes) in /mnt/webm/a1/34/53971734/htdocs/excellenzwebshop/system/helper/tcpdf/tcpdf.php on line 7328"

I saw a few commonts in the Opencart forum, but no concrete answers yet. What could be the cause of this (I also removed cache, but no results). 

Thanks in advance,

**Comment by mithereal** [comment]
i am unable to reproduce

**Comment by Releaff** [comment]
Can you check in my website to see the issue? Please give me your mailadres and I will send you my FTP login. Thanks.

**Comment by mithereal** [comment]
looks to be a php issue or image size issue see here http://php.net/manual/en/function.imagepng.php#104913
it may be an issue with opencarts image function not releasing the image from memory or just too big of an image in memory, or a hosting issue related to cache, i did have this issue on opencart 1.x versions i dont use 1.5 anymore nor support it, this works ok on 2.x ill be glad to look if i can fix i will for a small fee.

**Comment by mithereal** [comment]
mithereal@gmail.com
