### ISSUE TITLE
PHP Notice: Error: Could not load helper tcpdf/config/lang/eng!

### ISSUE THREAD

**Issue by arebias** [mithereal/opencart-pdf-catalog#5]
I don't know what I have mis-configured but I have tried all I know so if someone can help me; I can see that example page just fine, when I try to view PDF catalog I get a pop up window with nothing but a blank screen. The error log in OpenCart says:

"PHP Notice: Error: Could not load helper tcpdf/config/lang/eng! in /home/my_username/public_html/tcd/vqmod/vqcache/vq2-system_engine_loader.php on line 36"

Anyone know why this is conflicting with vqmod or is there some definition I need to include in the vqmod configuration? 

I am lost!!!!

**Comment by mithereal** [comment]
it seems as you have the wrong version of tcpdf installed please use the versions listed in the description
