### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ghost** [mithereal/opencart-pdf-catalog#7]
Iv'e just updated my TCPDF to TCPDF6 and get an error when trying to create the PDF.  The error looks like this:

Warning: file_get_contents(/home/t/torshamm/www/textiltryck/system/helper/tcpdf/examples/images/../pdf_catalog_default_logo.png): failed to open stream: No such file or directory in /home/t/torshamm/www/textiltryck/system/helper/tcpdf/include/tcpdf_static.php on line 2804TCPDF ERROR: [Image] Unable to get the size of the image: /home/t/torshamm/www/textiltryck/system/helper/tcpdf/examples/images/../pdf_catalog_default_logo.png

I just can't get the path to the logo alright. How will I do to get the right path? And where is the logo supposed to be?

**Comment by aszaunmi** [comment]
I placed an open issue up 2 months back and have not heard back from anyone on my open issue.

**Comment by mithereal** [comment]
I have uploaded a new version 2.8 on opencart.com this may fix your issues I will be pushing to github soon
