### ISSUE TITLE
Add Description product in pdf

### ISSUE THREAD

**Issue by mgg1** [mithereal/opencart-pdf-catalog#8]
Hi!

First: I enjoy the plugin! Thak you for this free plugin!

i have two questions:

the first:

i wish to add the description products in the PDF.. how i can do this?

The second:

I want do a new style in the pdf (clean, for example, the tables) and set one product per page with a new desing. It's posible do this?

I be waiting your answer! thank you a lot, again!

Mariano

(Sorry for my English... i try to do the best... :-p

**Comment by gondelle** [comment]
Hello, I installed the module pdf and I get this error:

Notice: Error: Could not load helper tcpdf/tcpdf! in /home/mascotas/public_html/vqmod/vqcache/vq2-system_engine_loader.php on line 36

**Comment by poortyweb** [comment]
Hello gondelle, Have you tried to clean the cache vQmod manager?

**Comment by gondelle** [comment]
Do not know how to do ...

Mascotas Modernas
Fátima Gómez Gondelle
info@mascotasmodernas.com
www.mascotasmodernas.com

**Comment by poortyweb** [comment]
You search vQmod Manager,  The second tab press clear.

**Comment by divira** [comment]
If I check Display Item Description:, PDF created is blank. Any idea?
