### ISSUE TITLE
Problem in pdfcatalog in 1.5.5.1

### ISSUE THREAD

**Issue by antstyl** [mithereal/opencart-pdf-catalog#9]
Getting the following error when choosing a category to create the pdf:

104Warning: imagefilledrectangle() expects parameter 1 to be resource, boolean given in /var/www/vhosts/katoikiashop.gr/steva/system/library/image.php on line 107Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in /var/www/vhosts/katoikiashop.gr/steva/system/library/image.php on line 109Warning: file_get_contents(image/cache/data/VENUS/GYALINA-EIDH/10123298-0x0.jpg) [function.file-get-contents]: failed to open stream: No such file or directory in /var/www/vhosts/katoikiashop.gr/steva/system/helper/tcpdf/include/tcpdf_static.php on line 2804TCPDF ERROR: [Image] Unable to get the size of the image: image/cache/data/VENUS/GYALINA-EIDH/10123298-0x0.jpg

**Comment by mithereal** [comment]
Looks to be a permissions problem
